Gaussian elimination and finding the inverse matrix

In [5]:
import numpy as np

In [6]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
aInv = np.linalg.inv(a)
aInv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
b = np.array([5, 11])
b

array([ 5, 11])

In [9]:
x = np.dot(aInv, b)
x

array([1., 2.])

In [10]:
np.dot(a, x)

array([ 5., 11.])